## String 
## iteration in String 
s="Geeksforgeeks"
for char in s:
    print(char)
## Function s.split() Uses to Split the Word 

## List Data Structure 

a=[1,2,"Hemanth "]
print(type(a[2]))     ## To find out what kind of data
# ;List can be created  by simply like a=[2]*7 now the List will Conatin[2,2,2,2,2]
S=["Hemanth","Gowda","Kuvempuu"] ## Iteration Type1
for s in S:
    print(s)
## Iteration Type2
for i in  range(0,len(S),1):
    print(s[i])
      
    
    